
from typing import Literal, Union
from pathlib import Path

DEFAULT_TASK = "TheRock"

TOO_LONG_DIDNT_READ = False
DISPLAY_DISKFILESYSTEM = False
DISPLAY_SYSTEM_INFO = True
DISPLAY_CCACHE_MODE:Literal["sv", "xv", "pv", "verbose"] = False
DISPLAY_SCCACHE_MODE = False
DISPLAY_LLVM = False
DISPLAY_ROCM = False
DISABLE_ANSI_COLOR = False
DISABLE_TEST = False
CLEAR_HOST = False

JSON_OUTPUT = False

ROCM_HOME: Union[Literal["", "build_dist"], str] = ""


THEROCK_BUILD_DIAGNOSE_SYSTEM_VERSION   =   "0.3.0"
THRROCK_REQUIRED_PYTHON_VERSION_MIN     =   "3.10.0"
THEROCK_DEPRECATED_PYTHON_VERSION_MAX   =   "3.9.15"
THRROCK_REQUIRED_NINJA_VERSION_MIN      =   "1.13.1"
THEROCK_REQUIRED_CMAKE_BEHAVIOR         =   "Default"


