

from typing import Literal, get_args, TypedDict, Union
from pathlib import Path

AMD_LLVM_COMPOMENTS_TYPEHINT = Literal[
    "amdclang",
    "amdclang++",
    "amdclang-cl",
    "amdclang-cpp",
    "amdgpu-arch",
    "amdflang",
    "amdlld",
    "amdllvm",
    "amd-llvm-spirv",
    "clang",
    "clang++",
    "clang-cl",
    "clangd",
    "clang-repl",
    "clang-tblgen",
    "clang-tidy",
    "flang",
    "flang-new",
    "flang1",
    "flang2",
    "hipcc",
    "hipify-clang",
    "hipInfo",
    "lld",
    "ld.lld",
    "ld64.lld",
    "lld-link",
    "llc",
    "lli",
    "llvm-ar",
    "llvm-as",
    "llvm-config",
    "llvm-cov",
    "llvm-cvtres",
    "llvm-cxxdump",
    "llvm-cxxflit",
    "llvm-cxxmap",
    "llvm-dis",
    "llvm-diff",
    "llvm-dlltool",
    "llvm-dwarfdump",
    "llvm-dwp",
    "llvm-exegesis",
    "llvm-gsymutil",
    "llvm-ifs",
    "llvm-jitlink",
    "llvm-lib",
    "llvm-link",
    "llvm-lipo",
    "llvm-lto",
    "llvm-lto2",
    "llvm-mc",
    "llvm-mca",
    "llvm-ml",
    "llvm-mt",
    "llvm-nm",
    "llvm-objcopy",
    "llvm-objdump",
    "llvm-pdbutil",
    "llvm-profgen",
    "llvm-rc",
    "llvm-ranlib",
    "llvm-readelf",
    "llvm-readobj",
    "llvm-strip",
    "llvm-symbolizer",
    "llvm-tblgen",
    "llvm-windres",
    "nvptx-arch",
    "opt",
    "wasm-ld",
]

AMD_LLVM_CONFIGURE_TYPEHINT = Literal[
    "LLVM Configured",
    "LLVM DIR",
    "LLVM Version",
    "LLVM Dist",
    "HIP Version",
    "AMD HIP SDK version",
    "LLVM Host Triple",
    "LLVM Target Triple",
    "LLVM Targets",
    "LLVM Enabled RTTI",
    "LLVM Binary Dir",
    "LLVM Include Dir",
    "LLVM Library Dir",
    "LLVM LD Library Dir",
    "LLVM CMake dir",
    "LLVM cflags",
    "LLVM cxxflags",
    "LLVM cppflags",
    "LLVM ldflags",
]

AMD_LLVM_TOOLS: list[AMD_LLVM_COMPOMENTS_TYPEHINT] = list(get_args(AMD_LLVM_COMPOMENTS_TYPEHINT))

LLVM_DIST_TYPEHINT = Literal["AMD-LLVM", "HIP_SDK", "AOCC", "VS20XX", "3rd-Party"]


LLVMConfigDict = dict[AMD_LLVM_CONFIGURE_TYPEHINT, Union[str, Path]]
LLVMToolsDict = dict[AMD_LLVM_COMPOMENTS_TYPEHINT, Union[str, Path]]
AMDLLVM_TYPEHINT = TypedDict("MyDictType", {
    "LLVM Configuration": LLVMConfigDict,
    "LLVM Toolchain": LLVMToolsDict
})
